---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mssql-operator-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mssql.popul.io
  resources:
  - backups
  - databases
  - databaseusers
  - logins
  - permissions
  - restores
  - schemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mssql.popul.io
  resources:
  - backups/finalizers
  - databases/finalizers
  - databaseusers/finalizers
  - logins/finalizers
  - permissions/finalizers
  - restores/finalizers
  - schemas/finalizers
  verbs:
  - update
- apiGroups:
  - mssql.popul.io
  resources:
  - backups/status
  - databases/status
  - databaseusers/status
  - logins/status
  - permissions/status
  - restores/status
  - schemas/status
  verbs:
  - get
  - patch
  - update
