//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hand (kubebuilder unavailable). DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// --- Database ---

func (in *Database) DeepCopyInto(out *Database) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Database) DeepCopy() *Database {
	if in == nil {
		return nil
	}
	out := new(Database)
	in.DeepCopyInto(out)
	return out
}

func (in *Database) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DatabaseList) DeepCopyInto(out *DatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Database, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DatabaseList) DeepCopy() *DatabaseList {
	if in == nil {
		return nil
	}
	out := new(DatabaseList)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	in.Server.DeepCopyInto(&out.Server)
	if in.Collation != nil {
		in, out := &in.Collation, &out.Collation
		*out = new(string)
		**out = **in
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(DeletionPolicy)
		**out = **in
	}
}

func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseStatus) DeepCopyInto(out *DatabaseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DatabaseStatus) DeepCopy() *DatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// --- Login ---

func (in *Login) DeepCopyInto(out *Login) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Login) DeepCopy() *Login {
	if in == nil {
		return nil
	}
	out := new(Login)
	in.DeepCopyInto(out)
	return out
}

func (in *Login) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LoginList) DeepCopyInto(out *LoginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Login, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *LoginList) DeepCopy() *LoginList {
	if in == nil {
		return nil
	}
	out := new(LoginList)
	in.DeepCopyInto(out)
	return out
}

func (in *LoginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LoginSpec) DeepCopyInto(out *LoginSpec) {
	*out = *in
	if in.Server.Port != nil {
		in, out := &in.Server.Port, &out.Server.Port
		*out = new(int32)
		**out = **in
	}
	if in.Server.TLS != nil {
		in, out := &in.Server.TLS, &out.Server.TLS
		*out = new(bool)
		**out = **in
	}
	if in.DefaultDatabase != nil {
		in, out := &in.DefaultDatabase, &out.DefaultDatabase
		*out = new(string)
		**out = **in
	}
	if in.ServerRoles != nil {
		in, out := &in.ServerRoles, &out.ServerRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(DeletionPolicy)
		**out = **in
	}
}

func (in *LoginSpec) DeepCopy() *LoginSpec {
	if in == nil {
		return nil
	}
	out := new(LoginSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *LoginStatus) DeepCopyInto(out *LoginStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *LoginStatus) DeepCopy() *LoginStatus {
	if in == nil {
		return nil
	}
	out := new(LoginStatus)
	in.DeepCopyInto(out)
	return out
}

// --- DatabaseUser ---

func (in *DatabaseUser) DeepCopyInto(out *DatabaseUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DatabaseUser) DeepCopy() *DatabaseUser {
	if in == nil {
		return nil
	}
	out := new(DatabaseUser)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DatabaseUserList) DeepCopyInto(out *DatabaseUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DatabaseUserList) DeepCopy() *DatabaseUserList {
	if in == nil {
		return nil
	}
	out := new(DatabaseUserList)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DatabaseUserSpec) DeepCopyInto(out *DatabaseUserSpec) {
	*out = *in
	if in.Server.Port != nil {
		in, out := &in.Server.Port, &out.Server.Port
		*out = new(int32)
		**out = **in
	}
	if in.Server.TLS != nil {
		in, out := &in.Server.TLS, &out.Server.TLS
		*out = new(bool)
		**out = **in
	}
	if in.DatabaseRoles != nil {
		in, out := &in.DatabaseRoles, &out.DatabaseRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *DatabaseUserSpec) DeepCopy() *DatabaseUserSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseUserSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseUserStatus) DeepCopyInto(out *DatabaseUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DatabaseUserStatus) DeepCopy() *DatabaseUserStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseUserStatus)
	in.DeepCopyInto(out)
	return out
}

// --- ServerReference ---

func (in *ServerReference) DeepCopyInto(out *ServerReference) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(bool)
		**out = **in
	}
}

func (in *ServerReference) DeepCopy() *ServerReference {
	if in == nil {
		return nil
	}
	out := new(ServerReference)
	in.DeepCopyInto(out)
	return out
}
