apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mssql-operator.fullname" . }}-manager
  labels:
    {{- include "mssql-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["mssql.popul.io"]
    resources: ["databases", "logins", "databaseusers", "schemas", "permissions", "backups", "restores", "scheduledbackups", "sqlservers", "availabilitygroups", "agfailovers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["mssql.popul.io"]
    resources: ["databases/status", "logins/status", "databaseusers/status", "schemas/status", "permissions/status", "backups/status", "restores/status", "scheduledbackups/status", "sqlservers/status", "availabilitygroups/status", "agfailovers/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["mssql.popul.io"]
    resources: ["databases/finalizers", "logins/finalizers", "databaseusers/finalizers", "schemas/finalizers", "permissions/finalizers", "backups/finalizers", "restores/finalizers", "scheduledbackups/finalizers", "sqlservers/finalizers", "availabilitygroups/finalizers", "agfailovers/finalizers"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mssql-operator.fullname" . }}-manager
  labels:
    {{- include "mssql-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mssql-operator.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "mssql-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
